import localFont from "next/font/local";
import "./globals.css";
import {Itim} from 'next/font/google';
import { Weight } from "lucide-react";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const itim=Itim({subsets:['latin'],weight:'400'})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={itim.className}
       
      >
        <Provider>
          {children}
        </Provider>
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
